const UPLOAD_USER_IMAGE_DIRECTORY = "public/images/users";
const MAX_UPLOAD_FILE_SIZE = 2097152; // 2MB
const ALLOW_UPLOAD_FILE_TYPE = ["jpg", "jpeg", "png", "JPG", "JPEG", "PNG"];

module.exports = { UPLOAD_USER_IMAGE_DIRECTORY, MAX_UPLOAD_FILE_SIZE, ALLOW_UPLOAD_FILE_TYPE };
